project:
  type: website
  output-dir: docs

website:
  title: "IWPP_0802"
  navbar: false
  site-url: "https://clarafontdevila.github.io/IWPP_0802/"
  image: "IWPP26_Preview.png" 
  open-graph: true
  twitter-card:
    image: "IWPP26_Preview.png"
    card-style: summary_large_image
    
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false
    link-citations: false
    anchor-sections: false

editor: visual