project:
  type: website
  output-dir: docs

website:
  title: "IWPP_0802"
  navbar: false
  
open-graph:
    image: "https://clarafontdevila.github.io/IWPP_0802/images/IWPP26_Preview.png"
    title: ""        
    description: ""  
    url: "https://clarafontdevila.github.io/IWPP_0802/"
    
twitter:           
    card: summary_large_image
    image: "https://clarafontdevila.github.io/IWPP_0802/images/IWPP26_Preview.png"
    title: ""        
    description: ""  
    url: "https://clarafontdevila.github.io/IWPP_0802/"
    
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false
    link-citations: false
    anchor-sections: false

editor: visual