project:
  type: website
  output-dir: docs

website:
  title: "IWPP_0802"
  navbar: false
  image: "http://clarafontdevila.github.io/IWPP_0802/logo_iwpp.png" 
  open-graph: true
    
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false
    link-citations: false
    anchor-sections: false

editor: visual